@startuml ClassDiagram
'skinparam Style strictuml

' Set global class color
skinparam class {
    BackgroundColor LightBlue
    BorderColor Black
}

interface SimpleIf <<interface>> {

}

class SignalGenSmBase <<component>> {

}

class SignalGen <<component>> {

}

class Simple <<state-machine>> {

}


class SignalGenComponentBase {

}

SignalGenSmBase <|-- SignalGen : Inheritance
SignalGenComponentBase <|-- SignalGenSmBase : Inheritance
SignalGenSmBase .right.|> SimpleIf : Implements
SignalGenSmBase *-- Simple : Composition

@enduml