@startuml ClassDiagram
'skinparam Style strictuml

' Set global class color
skinparam class {
    BackgroundColor LightBlue
    BorderColor Black
}

interface StateMachineIf <<interface>> {

}

class StateMachineBase <<component>> {

}


class StateMachine <<state-machine>> {

}

class ComponentImpl <<component>> {

}


class ComponentBase {

}

StateMachineBase <|-- ComponentImpl : Inheritance
ComponentBase <|-- StateMachineBase : Inheritance
StateMachineBase .right.|> StateMachineIf : Implements
StateMachineBase *-- StateMachine : Composition

@enduml