
@startuml

[*] --> OFF :/initialAction()

state OFF {
    [*] --> Far
    state Far {
        Far:Entry: farEntry()
        Far:Exit: farExit()
    }
}

state ON {
    [*] --> Bar
    state Bar {
        Bar:Entry: barEntry()
        Bar:Exit: barExit()
    }
}

state c1 <<choice>>
state c2 <<choice>>
state c3 <<choice>>
state c5 <<choice>>

ON --> OFF: Ev2
OFF --> c1: Ev1
c1 --> OFF: /a1()
c1 --> c2: [g1()]/b2()
c2 --> OFF: /a2()
c2 --> c3: [g2()]/b3()
c3 --> OFF: /a3()
c3 --> ON: [g3()]/b4()
OFF --> c5: Ev2 [g4()]/a5()
c5 --> OFF: [g5()]/a4()
c5 --> ON: /a6()

@enduml
