
@startuml

[*] --> S1

state S1 {
    S1:Entry: s1Entry(); s1Entry2(); foo(1)
    S1:Exit: s1Exit(); s1Exit2(); foo(2)
}

state S2 {
    S2:Entry: s2Entry(10); s2Entry2(20); foo(4)
    S2:Exit: s2Exit(); s2Exit2()
}

S1 --> S2: EV1[g1(e)]
S2 --> S1: EV1/a1(5); a2(e); foo(3)
S1 --> S2: EV2[g2(6)]

@enduml
