
@startuml

[*] --> OFF

state OFF {
    [*] --> Diag
    OFF:Entry: OffEntry()
    OFF:Exit: OffExit()
    state Diag {
        Diag:Entry: DiagEntry()
        Diag:Exit: DiagExit()
    }
}

state ON {
    [*] --> Init
    ON:Entry: OnEntry()
    ON:Exit: OnExit()
    state Init {
        Init:Entry: InitEntry()
        Init:Exit: InitExit()
    }
}

state c1 <<choice>>
ON --> OFF: EV1
OFF --> c1: EV1
c1 --> OFF: [g1()]
c1 --> ON: /a1()

@enduml
